### ISSUE TITLE
Multiple hierarchies for facilities

### ISSUE THREAD

**Issue by citizenrich** [openhie/facility-recon#19]
The use case is to associate facilities with more than one hierarchy. IIUC this is a limitation of the FHIR specification in that location resources can only have one hierarchy.

**Comment by ereynolds** [comment]
I may not be understanding, but if other facility lists do not have the exact same hierarchy then the tool will not be able to compare facilities between the two lists?

**Comment by citizenrich** [comment]
This is for a situation in which a facility, for example a hospital, is in multiple hierarchies at the same time. It is part of a 'district' but also in a sub county, which is in a county, which is in a district. This use case is difficult because the FHIR standard only allows on hierarchy for a Location Resource.

**Comment by ni-ka** [comment]
It would be good to add some real-world example datasets of this.

**Comment by citizenrich** [comment]
Completed. Also, future work is in the GOFR repo: https://github.com/intrahealth/gofr
