### ISSUE TITLE
Ability to add RTL translations

### ISSUE THREAD

**Issue by citizenrich** [openhie/facility-recon#26]

**Comment by ereynolds** [comment]
hi, I think you mentioned that the ability to have UI in French was in scope - as this would be a requirement for Guinea/other francophone countries.  (as well as for other non English speaking countries)

**Comment by ereynolds** [comment]
never mind, I see now there's another issue that covers this. thanks!

**Comment by citizenrich** [comment]
Superceded by GOFR repo.
