### ISSUE TITLE
Match on flat list with no hierarchy

### ISSUE THREAD

**Issue by citizenrich** [openhie/facility-recon#8]
Ability to match based just a list of facilities with no levels.

**Comment by ereynolds** [comment]
Hi, I'm imagining in the case of Guinea that organizations may have facilities under Districts but not sub-Districts - in that case if I'm understanding correctly Guinea DHIS 2 based facility list could not be compared with such a list.

**Comment by citizenrich** [comment]
It's a great question, about mismatching hierarchies. @lduncan-intrah thoughts?

**Comment by lduncan-intrah** [comment]
If it is a matter of having more or less levels, but the levels match, then the existing system can handle that.  For example if one source has Region and District and another has Region, District, and County, then the system can use the Districts for the parent comparison.  If the hierarchies don't match at all (e.g. using administrative districts vs. health delivery districts) then we would have an option to ignore the hierarchy completely and only compare the lowest (facility) level.

**Comment by citizenrich** [comment]
This feature was added as a setting.
